# Generated by Django 3.2 on 2021-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('ISBN', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=500)),
                ('availability', models.BooleanField(default=True)),
                ('img', models.URLField(max_length=2083)),
                ('url', models.URLField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('requestid', models.IntegerField()),
                ('approvetime', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('bookid', models.IntegerField()),
                ('requesttime', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('issueid', models.IntegerField()),
                ('returntime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
