# Generated by Django 3.2 on 2021-04-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='availability',
            new_name='available',
        ),
    ]
