# Generated by Django 3.2 on 2021-04-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_availability_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
