# Generated by Django 3.2 on 2021-04-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_request_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='return',
            name='userid',
        ),
    ]
