# Generated by Django 3.2 on 2021-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210421_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
