# Generated by Django 3.2 on 2021-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210423_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Book_icon_%28closed%29_-_Blue_and_gold.svg/343px-Book_icon_%28closed%29_-_Blue_and_gold.svg.png', max_length=2083),
        ),
    ]
