# Generated by Django 3.2 on 2021-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.URLField(blank=True, max_length=2083),
        ),
    ]
